### ISSUE TITLE
math equations in downloaded epub file are displayed in raw format

### ISSUE THREAD

**Issue by JackieMium** [winterwang/LSHTMlearningnote#1]
First, I'd like to thank you for this book. Great jod!

I am trying to download a epub copy so that I can read it on my phone or Kindle. But I've found that there are a lots of math equations showing up wrong in the file:

![screenshot_2019-01-15_13-29-49](https://user-images.githubusercontent.com/12944832/51160660-f4703c00-18c9-11e9-9be2-bc94c8a7ea31.png)

I tried to converted it to a PDF file and the still the equations were displaying like this.

BTW, I've seen other books on bookdown privode pdf file for downloading and codes and equations  are fine. If it helps anyway.

**Comment by winterwang** [comment]
Thanks for the comment. I've noticed that a long time ago. Now I have finally made the changes in the raw math codes to the correct ones. You can have the epub file with math equation shown normally. However, I cannot recommend reading the downloaded file since I am still updating the content quite frequently. 
Therefore, the best way would still be reading it online. 

Enjoy and good luck with your learning!
